[package]
name = "browsercfg"
version = "0.1.0"
edition = "2024"
description = "A tool intended to help managing Firefox-based AutoConfig projects"
license = "GPL-3.0"
authors = ["CosmoCreeper <cos.om@tuta.io>"]
repository = "https://github.com/CosmoCreeper/browsercfg"
readme = "README.md"
keywords = ["firefox", "autoconfig", "browsercfg", "browsers"]
categories = ["command-line-interface", "command-line-utilities"]

[dependencies]
indexmap = "2.13.1"
inquire = "0.9.4"
regex = "1.12.3"
reqwest = { version = "0.13.2", features = ["blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[target.'cfg(windows)'.dependencies]
sevenz-rust = "0.6"

[target.'cfg(target_os = "linux")'.dependencies]
tar = "0.4.45"
xz2 = "0.1.7"
